// v4 presentation-time demo (092726).
// 18 trials reintroduced from Pilot 1 / Pilot 2 (easy, good-reliability items that were
// dropped and do not overlap, image-for-image, with the current 76-trial set or Pilot 3).
// Ordered easiest-to-hardest (pilot accuracy desc, item-rest correlation as tiebreak).
// presentationTime (ms): how long the study image is visible before it is hidden; the
// choice buttons remain up and clickable indefinitely after that (response_ends_trial,
// no hard trial_duration -- the trial does NOT auto-end when presentationTime elapses).
// Schedule: trials 1-2 = 1000ms, 3-10 = 500ms, 11-14 = 750ms, 15-18 = 1000ms.
// corrRes is 0-based; slots/emptySlot are randomized live per participant in index.html,
// not stored here (see the main texture engine for the same convention).
var trials = [
  {"trial": 1, "study": "t16_coral0744_study.png", "choices": ["t16_coral0744_part1_match.png", "t16_coral0753_part2_distractor.png", "t16_coral0741_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "easy", "category": "coral", "db": "stf", "crossed": false, "choice_db": ["stf", "stf", "stf"], "choice_category": ["coral", "coral", "coral"], "answer_part": 1, "presentationTime": 1000, "sourcePilot": "pilot1", "sourceOrigTrial": 16, "pilotAccuracy": 0.967, "pilotItemRest": 0.436},
  {"trial": 2, "study": "t07_gauzy0091_study.png", "choices": ["t07_gauzy0091_part1_match.png", "t07_gauzy0173_part2_distractor.png", "t07_gauzy0194_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "easy", "category": "gauzy", "db": "dtd", "crossed": false, "choice_db": ["dtd", "dtd", "dtd"], "choice_category": ["gauzy", "gauzy", "gauzy"], "answer_part": 1, "presentationTime": 1000, "sourcePilot": "pilot1", "sourceOrigTrial": 7, "pilotAccuracy": 0.967, "pilotItemRest": 0.368},
  {"trial": 3, "study": "t46_fat0960_study.png", "choices": ["t46_fat0960_part1_match.png", "t46_fat0963_part2_distractor.png", "t46_fat0957_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "med", "category": "fat", "db": "stf", "crossed": false, "choice_db": ["stf", "stf", "stf"], "choice_category": ["fat", "fat", "fat"], "answer_part": 1, "presentationTime": 500, "sourcePilot": "pilot1", "sourceOrigTrial": 46, "pilotAccuracy": 0.967, "pilotItemRest": 0.368},
  {"trial": 4, "study": "t16_cheesecloth0556_study.png", "choices": ["t16_cheesecloth0556_part1_match.png", "t16_cheesecloth0560_part2_distractor.png", "t16_cheesecloth0558_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "easy", "category": "cheesecloth", "db": "stf", "crossed": false, "choice_db": ["stf", "stf", "stf"], "choice_category": ["cheesecloth", "cheesecloth", "cheesecloth"], "answer_part": 1, "presentationTime": 500, "sourcePilot": "pilot2", "sourceOrigTrial": 16, "pilotAccuracy": 0.94, "pilotItemRest": 0.1489},
  {"trial": 5, "study": "t43_stained0079_study.png", "choices": ["t43_stained0079_part1_match.png", "t43_stained0138_part2_distractor.png", "t43_stained0129_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "med", "category": "stained", "db": "dtd", "crossed": false, "choice_db": ["dtd", "dtd", "dtd"], "choice_category": ["stained", "stained", "stained"], "answer_part": 1, "presentationTime": 500, "sourcePilot": "pilot1", "sourceOrigTrial": 43, "pilotAccuracy": 0.933, "pilotItemRest": 0.221},
  {"trial": 6, "study": "t34_stained0061_study.png", "choices": ["t34_stained0061_part1_match.png", "t34_stained0062_part2_distractor.png", "t34_stained0055_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "med", "category": "stained", "db": "dtd", "crossed": false, "choice_db": ["dtd", "dtd", "dtd"], "choice_category": ["stained", "stained", "stained"], "answer_part": 1, "presentationTime": 500, "sourcePilot": "pilot1", "sourceOrigTrial": 34, "pilotAccuracy": 0.9, "pilotItemRest": 0.391},
  {"trial": 7, "study": "t23_amethyst0059_study.png", "choices": ["t23_amethyst0059_part1_match.png", "t23_garnet1228_part2_distractor.png", "t23_quartz2373_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "easy", "category": "amethyst", "db": "stf", "crossed": false, "choice_db": ["stf", "stf", "stf"], "choice_category": ["amethyst", "garnet", "quartz"], "answer_part": 1, "presentationTime": 500, "sourcePilot": "pilot2", "sourceOrigTrial": 23, "pilotAccuracy": 0.9, "pilotItemRest": 0.2246},
  {"trial": 8, "study": "t15_bumpy0131_study.png", "choices": ["t15_blowfish13s_part1_distractor.png", "t15_bumpy0147_part2_distractor.png", "t15_bumpy0131_part3_match.png"], "corrRes": 2, "trialType": "test", "level": "easy", "category": "bumpy", "db": "dtd", "crossed": true, "choice_db": ["tgs", "dtd", "dtd"], "choice_category": ["blowfish", "bumpy", "bumpy"], "answer_part": 3, "presentationTime": 500, "sourcePilot": "pilot1", "sourceOrigTrial": 15, "pilotAccuracy": 0.867, "pilotItemRest": 0.387},
  {"trial": 9, "study": "t29_corduroy42d-scale_4_im_10_col_study.png", "choices": ["t29_corduroy42d-scale_4_im_10_col_part1_match.png", "t29_corduroy42d-scale_7_im_3_col_part2_distractor.png", "t29_corduroy42d-scale_7_im_10_col_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "easy", "category": "corduroy", "db": "kt2", "crossed": false, "choice_db": ["kt2", "kt2", "kt2"], "choice_category": ["corduroy", "corduroy", "corduroy"], "answer_part": 1, "presentationTime": 500, "sourcePilot": "pilot2", "sourceOrigTrial": 29, "pilotAccuracy": 0.86, "pilotItemRest": 0.3654},
  {"trial": 10, "study": "t24_stratified0102_study.png", "choices": ["t24_stratified0102_part1_match.png", "t24_stratified0163_part2_distractor.png", "t24_stratified0165_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "easy", "category": "stratified", "db": "dtd", "crossed": false, "choice_db": ["dtd", "dtd", "dtd"], "choice_category": ["stratified", "stratified", "stratified"], "answer_part": 1, "presentationTime": 500, "sourcePilot": "pilot2", "sourceOrigTrial": 24, "pilotAccuracy": 0.86, "pilotItemRest": 0.1925},
  {"trial": 11, "study": "t19_linen1668_study.png", "choices": ["t19_linen1668_part1_match.png", "t19_linen1671_part2_distractor.png", "t19_linen1677_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "easy", "category": "linen", "db": "stf", "crossed": false, "choice_db": ["stf", "stf", "stf"], "choice_category": ["linen", "linen", "linen"], "answer_part": 1, "presentationTime": 750, "sourcePilot": "pilot1", "sourceOrigTrial": 19, "pilotAccuracy": 0.833, "pilotItemRest": 0.376},
  {"trial": 12, "study": "t49_corduroy42d-scale_4_im_8_col_study.png", "choices": ["t49_corduroy42d-scale_4_im_8_col_part1_match.png", "t49_corduroy42d-scale_8_im_5_col_part2_distractor.png", "t49_corduroy42d-scale_6_im_7_col_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "med", "category": "corduroy", "db": "kt2", "crossed": false, "choice_db": ["kt2", "kt2", "kt2"], "choice_category": ["corduroy", "corduroy", "corduroy"], "answer_part": 1, "presentationTime": 750, "sourcePilot": "pilot1", "sourceOrigTrial": 49, "pilotAccuracy": 0.833, "pilotItemRest": 0.277},
  {"trial": 13, "study": "t30_copper0724_study.png", "choices": ["t30_copper0724_part1_match.png", "t30_copper0721_part2_distractor.png", "t30_copper0716_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "easy", "category": "copper", "db": "stf", "crossed": false, "choice_db": ["stf", "stf", "stf"], "choice_category": ["copper", "copper", "copper"], "answer_part": 1, "presentationTime": 750, "sourcePilot": "pilot2", "sourceOrigTrial": 30, "pilotAccuracy": 0.82, "pilotItemRest": 0.1163},
  {"trial": 14, "study": "t55_lettuce_leaf23a-scale_4_im_5_col_study.png", "choices": ["t55_lettuce_leaf23a-scale_4_im_5_col_part1_match.png", "t55_lettuce_leaf23a-scale_5_im_11_col_part2_distractor.png", "t55_lettuce_leaf23a-scale_5_im_8_col_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "med", "category": "lettuce_leaf", "db": "kt2", "crossed": false, "choice_db": ["kt2", "kt2", "kt2"], "choice_category": ["lettuce_leaf", "lettuce_leaf", "lettuce_leaf"], "answer_part": 1, "presentationTime": 750, "sourcePilot": "pilot2", "sourceOrigTrial": 55, "pilotAccuracy": 0.8, "pilotItemRest": 0.3415},
  {"trial": 15, "study": "t19_cellophane0454_study.png", "choices": ["t19_cellophane0454_part1_match.png", "t19_plastic2250_part2_distractor.png", "t19_plastic2238_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "easy", "category": "cellophane", "db": "stf", "crossed": false, "choice_db": ["stf", "stf", "stf"], "choice_category": ["cellophane", "plastic", "plastic"], "answer_part": 1, "presentationTime": 1000, "sourcePilot": "pilot2", "sourceOrigTrial": 19, "pilotAccuracy": 0.74, "pilotItemRest": 0.1228},
  {"trial": 16, "study": "t44_silicon2738_study.png", "choices": ["t44_silicon2729_part1_distractor.png", "t44_silicon2738_part2_match.png", "t44_silicon2737_part3_distractor.png"], "corrRes": 1, "trialType": "test", "level": "med", "category": "silicon", "db": "stf", "crossed": false, "choice_db": ["stf", "stf", "stf"], "choice_category": ["silicon", "silicon", "silicon"], "answer_part": 2, "presentationTime": 1000, "sourcePilot": "pilot1", "sourceOrigTrial": 44, "pilotAccuracy": 0.733, "pilotItemRest": 0.366},
  {"trial": 17, "study": "t32_ice1459_study.png", "choices": ["t32_ice1462_part1_distractor.png", "t32_ice1462_part2_distractor.png", "t32_ice1459_part3_match.png"], "corrRes": 2, "trialType": "test", "level": "med", "category": "ice", "db": "stf", "crossed": false, "choice_db": ["stf", "stf", "stf"], "choice_category": ["ice", "ice", "ice"], "answer_part": 3, "presentationTime": 1000, "sourcePilot": "pilot1", "sourceOrigTrial": 32, "pilotAccuracy": 0.733, "pilotItemRest": 0.24},
  {"trial": 18, "study": "t28_granite1339_study.png", "choices": ["t28_granite1339_part1_match.png", "t28_granite1331_part2_distractor.png", "t28_granite1338_part3_distractor.png"], "corrRes": 0, "trialType": "test", "level": "med", "category": "granite", "db": "stf", "crossed": false, "choice_db": ["stf", "stf", "stf"], "choice_category": ["granite", "granite", "granite"], "answer_part": 1, "presentationTime": 1000, "sourcePilot": "pilot1", "sourceOrigTrial": 28, "pilotAccuracy": 0.7, "pilotItemRest": 0.214}
];
